name: printer_controller_pr3
description: Grants access to the printer from pure flutter applications without opening any native android activity.
version: 0.0.4
repository: https://github.com/FatihGeylan/printer_controller_pr3

environment:
  sdk: '>=2.19.2 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.example.printer_controller_pr3
        pluginClass: PrinterControllerPr3Plugin

